/*
 *  File: UserSchema.js
 *  Type: Schema
 *  Generated by: Mongoose-Fixture (v0.3.1)
 *
 *
 */

module.exports = function(mongoose, conn){

    var exportSchema = mongoose.Schema({
        /*
           this is an example, fillin with
           your own schema data
           NOTE: `id` was excluded, by default mongoose
           will use the standard mongo ObjectID so only
           define an `id` if you wish to override mongos default
        */
        name: {
            type:String
        },
        password: {
            type:String
        },
        email: {
            type:String
        },
        avatar: {
            type: String
        },
        tags: {
            type: Array
        },
        update_at: {
            type: Date
        }
    });

    // By Default we export the schema
    // You could alter this returning void
    // and registering your model with the db connection
    // conn.model('ModelName', exportSchema);
    return exportSchema;
};
