/*
 *  File: User.js
 *  Type: DataFixture
 *  Generated by: Mongoose-Fixture (v0.3.1)
 *
 */

// @callback must be returned
// expects (err, object)
// object can be an array of data-documents, or a kwarg['dataFixtures']
// mongoose is the instance of mongoose being used (has schemas)
// conn is the current native mongodb connection (will contain models)
module.exports = function(mongoose, conn, callback){

    // standard callback error
    var error = null;

    // create your data documents using object-literals
    var fixture = [];

    /*
     * Example of adding a data document/fixture item
     */
    fixture.push({
        // by not defining an _id mongoose-fixture
        // will by default set a mongo ObjectID
        // defining one manually will override mongoDB
        name:'johnny',
        password: '123',
        email: 'kkiiiu@gmail.com',
        avatar: 'avatar',
        tags:['test','data']
    });

    // mongoose-fixture expects implementor to return
    // the callback passed in context
    return callback(error, fixture);
};
